### ISSUE TITLE
Crash on Enable in 1.9 with v1.9.1.1 and v.1.9.1.3

### ISSUE THREAD

**Issue by kernschatten** [mastercake10/TimeIsMoney#1]
I boot the server with Bukkit because a worldgenerator seemed to have issues with Spigot and I noticed this crash... does this not work with Bukkit and only works with Spigot?

10.03 18:02:59 [Server] INFO You are running the latest version
10.03 18:02:59 [Server] INFO Checking version, please wait...
10.03 18:02:59 [Server] INFO This server is running CraftBukkit version git-Bukkit-dd016e7 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

10.03 17:58:29 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [custom.jar:git-Bukkit-dd016e7]
10.03 17:58:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [custom.jar:git-Bukkit-dd016e7]
10.03 17:58:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [custom.jar:git-Bukkit-dd016e7]
10.03 17:58:29 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[custom.jar:git-Bukkit-dd016e7]
10.03 17:58:29 [Server] INFO at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:124) ~[?:?]
10.03 17:58:29 [Server] INFO at de.Linus122.TimeIsMoney.Main.loadPayouts(Main.java:195) ~[?:?]
10.03 17:58:29 [Server] INFO java.lang.NullPointerException
10.03 17:58:29 [Server] ERROR Error occurred while enabling TimeIsMoney v10.0 (Is it up to date?)
10.03 17:58:29 [Server] WARN at java.lang.Thread.run(Thread.java:745)
10.03 17:58:29 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506)
10.03 17:58:29 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241)
10.03 17:58:29 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323)
10.03 17:58:29 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368)
10.03 17:58:29 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403)
10.03 17:58:29 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318)
10.03 17:58:29 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346)
10.03 17:58:29 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
10.03 17:58:29 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
10.03 17:58:29 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
10.03 17:58:29 [Server] WARN at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:124)
10.03 17:58:29 [Server] WARN at de.Linus122.TimeIsMoney.Main.loadPayouts(Main.java:192)
10.03 17:58:29 [Server] WARN java.lang.NullPointerException
10.03 17:58:29 [Server] INFO Enabling TimeIsMoney v10.0

**Comment by kernschatten** [comment]
and in 1.9.13

[09:10:16] [Server thread/INFO]: [TimeIsMoney] Enabling TimeIsMoney v10.0
[09:10:16] [Server thread/WARN]: java.lang.NullPointerException
[09:10:16] [Server thread/WARN]: 	at de.Linus122.TimeIsMoney.Main.loadPayouts(Main.java:192)
[09:10:16] [Server thread/WARN]: 	at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:124)
[09:10:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[09:10:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[09:10:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[09:10:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346)
[09:10:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318)
[09:10:16] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403)
[09:10:16] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368)
[09:10:16] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323)
[09:10:16] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241)
[09:10:16] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506)
[09:10:16] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[09:10:16] [Server thread/ERROR]: Error occurred while enabling TimeIsMoney v10.0 (Is it up to date?)
java.lang.NullPointerException
	at de.Linus122.TimeIsMoney.Main.loadPayouts(Main.java:195) ~[?:?]
	at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[custom.jar:git-Bukkit-4a8818c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [custom.jar:git-Bukkit-4a8818c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [custom.jar:git-Bukkit-4a8818c]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [custom.jar:git-Bukkit-4a8818c]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [custom.jar:git-Bukkit-4a8818c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by kernschatten** [comment]
Even though it didn't seem to enable, it still errored with:

[09:14:32] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to TimeIsMoney v10.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[custom.jar:git-Bukkit-4a8818c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Bukkit-4a8818c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [custom.jar:git-Bukkit-4a8818c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1930) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Bukkit-4a8818c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:679) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635) [custom.jar:git-Bukkit-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539) [custom.jar:git-Bukkit-4a8818c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at modules.atm.ATM.onClick(ATM.java:62) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[custom.jar:git-Bukkit-4a8818c]
	... 15 more

**Comment by mastercake10** [comment]
It works fine for me on spigot 1.7 - 1.9. But in the seconds error, it seems you did a configuration mistake maybe? Checkt that please.

**Comment by kernschatten** [comment]
This is what I'm looking at:

> give_money_every_second: 1200
afk_payout: false
info: You can add more payouts by copy and paste. Dont forget to change the number!
store-money-in-bank: false
payouts:
  1:
    payout_amount: 100
    max_payout_per_day: 1000
    permission:
  2:
    payout_amount: 100
    max_payout_per_day: 10000
    commands:
      - /give %player% diamond 1
    permission: tim.vip
message: "&aYou have got &c%money% &afor 20 minutes online time!"
message_payoutlimit_reached: "§cYou have reached the payoutlimit today. You got 0$"
message_afk: "&cYou ain't get no money while afk!"
message_actionbar: "&aYou have got &c%money% &afor 20 minutes online time!"
message_payoutlimit_reached_actionbar: "§cYou have reached the payoutlimit today. You got 0$"
message_afk_actionbar: "&cYou havn't got money because you were afk!"
display-messages-in-chat: true
display-messages-in-actionbar: false
display-messages-in-actionbar-time: 10
message_atm_noperms: "§cYou dont have permissions to use ATM's!"
message_atm_nomoneyinbank: "§cYou don't have enought money in bank!"
message_atm_nomoney: "§cYou don't have enought money!"
atm_title: "§cATM"
atm_withdraw: "§cWithdraw"
atm_deposit: "§cDeposit"
atm_balance: "§cBank balance:"
configuration-version: 10

**Comment by mastercake10** [comment]
You are using a old version - please update and generate a new config by deleting the old one.

**Comment by kernschatten** [comment]
As best I can tell, all is working now with this update:

> Finally I found out the error for non-spigot servers. The plain craftbukkit doesn't contain the method .getClickedInventory(), so i changed this to .getInventory();
> 
> - Fixed some craftbukkit incompatibilities
