### ISSUE TITLE
Console being spammed... 1.21.3

### ISSUE THREAD

**Issue by Remski01** [mastercake10/TimeIsMoney#117]
### What steps will reproduce the issue?  
1. Be an non OP player.
2. Be online.
3. Profit.

### What was supposed to happen?
Not spam the console.

### What happened instead? 
Spam the console.

### What version of TimeIsMoney are you using?  
1.9.10

### What Spigot version are you using? Paste the output of /version below.  
Paper version 1.21.3-76-master@27e4ddc

### What plugins do you have installed? Paste the output of /plugins below.  
Also happens with just TIM and required plugins. (Essentials/Luckperms)

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
```
[19:10:03 INFO]: Made Polski05 no longer a server operator
[19:10:04 WARN]: [TimeIsMoney] Task #80 for TimeIsMoney v1.9.10 generated an exception
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
        at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at TimeIsMoney-1.9.10.jar/de.Linus122.TimeIsMoney.Main.getApplicablePayoutsForPlayer(Main.java:292) ~[TimeIsMoney-1.9.10.jar:?]
        at TimeIsMoney-1.9.10.jar/de.Linus122.TimeIsMoney.Main.lambda$startPlaytimeWatcher$0(Main.java:180) ~[TimeIsMoney-1.9.10.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1803) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1664) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1329) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:10:05 INFO]: Made Polski05 a server operator
```
### Any additional information that you would like to provide that may be relevant to the issue?

```
payouts:
  1:
    payout_amount: 10
    max_payout_per_day: 1000
    # chance: 10
    permission: "timeismoney.base"
```

**Comment by mastercake10** [comment]
fixed in 1a51294
