### ISSUE TITLE
atm_title npe

### ISSUE THREAD

**Issue by drtshock** [mastercake10/TimeIsMoney#30]
### What version of TimeIsMoney are you using?  
TimeIsMoney version 1.9.6.5

### What Spigot version are you using? Paste the output of /version below.  
[18:08:54 INFO]: This server is running CraftBukkit version git-Spigot-e8ded36-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
```
output: [15:45:03 ERROR]: Could not pass event InventoryMoveItemEvent to TimeIsMoney v1.9.6.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-e8ded36-acbc348]

output: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-e8ded36-acbc348]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.TileEntityHopper.s(TileEntityHopper.java:217) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.TileEntityHopper.o(TileEntityHopper.java:134) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.TileEntityHopper.e(TileEntityHopper.java:119) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1501) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-e8ded36-acbc348]

output: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-e8ded36-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-e8ded36-acbc348]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException

output: 	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
at de.Linus122.TimeIsMoney.tools.Utils.CC(Utils.java:26) ~[?:?]
at de.Linus122.TimeIsMoney.ATM.onMove(ATM.java:222) ~[?:?]
at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]

output: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
... 13 more

```
### Any additional information that you would like to provide that may be relevant to the issue?
I run a shared hosting service called Minehut. I'm unable to view the player's configuration or other specific plugins, as well as unable to determine how to reproduce this issue. I think it's pretty clear though, they don't have the `atm_title` set in their config and it's throwing an NPE. Please assume that whenever you're grabbing something from the config that it won't be there, and you'll need a default and/or a null check. In this case, on this line here https://github.com/mastercake10/TimeIsMoney/blob/master/Plugin/src/main/java/de/Linus122/TimeIsMoney/ATM.java#L222.

This error is so spammy that it fills up logs to be over 100gb in a matter of a few hours.

**Comment by mastercake10** [comment]
Thanks for reporting this error.

However, if your users really want to disable the ATM feature, they should consider turning off the ATM (`enable_atm: false`). I don't see why people are emptying this string on purpose. Also, as a hoster, you should consider shrinking the maximal disk size for logs, since console errors are not unusual especially when plugins are misconfigured.

Despite this, I'll add a check for the `atm_title` property and turn the ATM off, so the event would not be triggered anymore.
