### ISSUE TITLE
different payout

### ISSUE THREAD

**Issue by iKaazeh** [mastercake10/TimeIsMoney#31]
### What steps will reproduce the issue?  
1.  I opened the config files 
2. I wrote this in the config file:   1:
    payout_amount: 70
    max_payout_per_day: 1000
     chance: 100
    permission: tim.FBI
(FBI is a group, I'm using LuckPerms)
3. In game the payout always remains $25

### What Spigot version are you using? Paste the output of /version below.  
[12:10:40 INFO]: This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
[12:12:49 INFO]: Plugins (48): LuckPerms, AnvilRestrict, Skript, Vehicles, ClearLag, CrackShot, AutoMessage, Chairs, Elevator, Lockette, HeadsPlus, ProtocolLib, Multiverse-Core, NoCheatPlus, TabX, SkinsRestorer, FastAsyncWorldEdit, iDisguise, SerialKey, BigDoors, AntiCraft, MovingThings, Hat, Vault, SimpleSit, LightAPI, Drugs, GUIPlus, Essentials, FastAsyncVoxelSniper, SimpleRename, HolographicDisplays, LiteBans, EssentialsXMPP, EssentialsProtect, VoxelSniper, EssentialsGeoIP, EssentialsChat, TimeIsMoney, Telecom, TAB, EssentialsSpawn, WorldEdit, Disease, ProtectionLib, FurnitureLib, DiceFurniture

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
```
[12:12:14] [Server thread/ERROR]: Cannot load plugins/TimeIsMoney/config.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 30, column 12:
         chance: 100
               ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:160) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:124) [TimeIsMoney.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 30, column 12:
         chance: 100
               ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:424) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	... 16 more
[12:12:14] [Server thread/ERROR]: Cannot load plugins/TimeIsMoney/config.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 30, column 12:
         chance: 100
               ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:127) [TimeIsMoney.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 30, column 12:
         chance: 100
               ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:424) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	... 15 more
[12:12:14] [Server thread/ERROR]: Cannot load plugins/TimeIsMoney/config.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 30, column 12:
         chance: 100
               ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:146) [TimeIsMoney.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 30, column 12:
         chance: 100
               ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:424) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	... 15 more
[12:12:14] [Server thread/ERROR]: Error occurred while enabling TimeIsMoney v1.9.6.5 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at de.Linus122.TimeIsMoney.tools.Utils.CC(Utils.java:26) ~[?:?]
	at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:183) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by iKaazeh** [comment]
[config.zip](https://github.com/mastercake10/TimeIsMoney/files/2936848/config.zip)

**Comment by mastercake10** [comment]
![image](https://user-images.githubusercontent.com/16278273/53895744-f71e2080-4032-11e9-9893-a33f885cfa95.png)
You need to format your config.yml properly. This is not an issue.
