### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by betasauce** [mastercake10/TimeIsMoney#34]
### What steps will reproduce the issue?  
1. While running the plugin on my server, seemingly at random time it will generate this exception.

### What was supposed to happen?
Not for it to throw a timeout exception.

### What happened instead? 
It threw the exception.

### What version of TimeIsMoney are you using?  
TimeIsMoney v1.9.6.5

### What Spigot version are you using? Paste the output of /version below.  
"This server is running CraftBukkit version git-Spigot-1eece4f-09a453a (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)"

### What plugins do you have installed? Paste the output of /plugins below.  
- ChatManager 3.4.6
- ChestShop
- Gringotts
- GroupManager
- HomeSpawn
- ModernLWC
- MyCommand
- PhantomSMP
- TimeIsMoney
- Vault
- WorldEdit
- WorldGuard

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
```
[18:10:53] [Craft Scheduler Thread - 6/WARN]: [TimeIsMoney] Plugin TimeIsMoney v1.9.6.5 generated an exception while executing task 24
org.gestern.gringotts.GringottsException: java.util.concurrent.TimeoutException
        at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:294) ~[?:?]
        at org.gestern.gringotts.GringottsAccount.getBalance(GringottsAccount.java:84) ~[?:?]
        at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:251) ~[?:?]
        at org.gestern.gringotts.api.impl.VaultConnector.getBalance(VaultConnector.java:81) ~[?:?]
        at de.Linus122.TimeIsMoney.Main.pay(Main.java:397) ~[?:?]
        at de.Linus122.TimeIsMoney.Main.lambda$onEnable$0(Main.java:166) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_212]
        at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:292) ~[?:?]
        ... 10 more

```
### Any additional information that you would like to provide that may be relevant to the issue?
The plugins seems to be working but the console will get flooded on occation with a few of these warnings, I haven't noticed what exactly causes it, just seems random as far as I can tell so far.

**Comment by mastercake10** [comment]
It seems that "Gringotts" (whatever this is) isn't able to handle multiple balance checks. Other economy plugins like Essentials work perfectly with TIM.

Therefore I suggest opening an issue on https://github.com/MinecraftWars/Gringotts. I'll close this for now.
