### ISSUE TITLE
Time is Money Problem 1.14.1 Fixing

### ISSUE THREAD

**Issue by Blueeyestar** [mastercake10/TimeIsMoney#36]
Spigot: CraftBukkit version git-Spigot-03bd4b0-342194e (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**My dev has now tried to fix Time is Money, but always get the same error and this running through. Do you as a programmer have a hint what I do wrong?**

[19:08:35] [Craft Scheduler Thread - 2/INFO]: [Vault] Checking for Updates ...
[19:08:36] [Server thread/WARN]: java.lang.NoSuchFieldException: title
[19:08:36] [Server thread/WARN]: at java.lang.Class.getField(Unknown Source)
[19:08:36] [Server thread/WARN]: at de.Linus122.TimeIsMoney.ATM.onMove(ATM.java:242)
[19:08:36] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:08:36] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:08:36] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:08:36] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Unknown Source)
[19:08:36] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[19:08:36] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:08:36] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520)
[19:08:36] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.TileEntityHopper.u(TileEntityHopper.java:220)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:135)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:670)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:369)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956)
[19:08:36] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801)
[19:08:36] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)
[19:08:36] [Server thread/WARN]: java.lang.NoSuchFieldException: title

**Comment by mastercake10** [comment]
Well, I don't have access to your source code, so I can't really tell you what's going on, but I think you're simply trying to access the title of the ATM which is no longer possible using directly the inventory object.
Hope that helps.
