### ISSUE TITLE
Could not pass event InventoryMoveItemEvent to TimeIsMoney v1.9.6.5 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by Blueeyestar** [mastercake10/TimeIsMoney#37]
Tim-Vers: Time is Money 1.9.6.6

Spigot: CraftBukkit version git-Spigot-03bd4b0-17da342 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

In the version comes a continuous loop of error.
I very much hope that this bug can be fixed. 

https://pastebin.com/i9mSVvPa

[06:16:20] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to TimeIsMoney v1.9.6.5
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-17da342]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-17da342]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.TileEntityHopper.u(TileEntityHopper.java:220) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:135) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:670) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:369) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot.jar:git-Spigot-03bd4b0-17da342]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
    at de.Linus122.TimeIsMoney.ATM.onMove(ATM.java:221) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-17da342]
    ... 13 more

**Comment by mastercake10** [comment]
Your error log says you're using TIM v1.9.6.5. Please update.

**Comment by Blueeyestar** [comment]
I downloaded it there, and it's still the same thing.

https://github.com/mastercake10/TimeIsMoney/releases/tag/1.9.6.6



[15:32:11] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to TimeIsMoney v1.9.6.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.u(TileEntityHopper.java:220) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:135) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:670) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:369) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_201]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_201]
	at de.Linus122.TimeIsMoney.ATM.onMove(ATM.java:221) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	... 13 more
