### ISSUE TITLE
[15:32:11] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to TimeIsMoney v1.9.6.6

### ISSUE THREAD

**Issue by Blueeyestar** [mastercake10/TimeIsMoney#38]
I downloaded it there, and it's still the same thing.

https://github.com/mastercake10/TimeIsMoney/releases/tag/1.9.6.6

Spigot-Vers:CraftBukkit version git-Spigot-03bd4b0-17da342 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

unfortunately doesn't change the result, unfortunately the error is still the same. Even if you rebuild the file.  :(
It is the most recent Spigot version available.

[15:42:52] [Server thread/INFO]: [TimeIsMoney] Enabling TimeIsMoney v1.9.6.6
[15:42:52] [Server thread/INFO]: [m
[15:42:52] [Server thread/ERROR]: [TimeIsMoney] Actionbars are not supported on your spigot version, sorry.
[15:42:52] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:42:52] [Server thread/INFO]: Done (18.992s)! For help, type "help"
[15:42:52] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to TimeIsMoney v1.9.6.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.u(TileEntityHopper.java:220) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:135) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:670) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:369) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_201]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_201]
	at de.Linus122.TimeIsMoney.ATM.onMove(ATM.java:221) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot-latest.jar:git-Spigot-03bd4b0-17da342]
	... 13 more

**Comment by mastercake10** [comment]
Can you give some more background information? So does the ATM work for you? Does this error appear occasionally?

**Comment by mastercake10** [comment]
### What steps will reproduce the issue?  
1. 
2. 
3. 

### What was supposed to happen?

### What happened instead? 

### What version of TimeIsMoney are you using?  

### What Spigot version are you using? Paste the output of /version below.  

### What plugins do you have installed? Paste the output of /plugins below.  

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
```
paste
error(s)
here
```
### Any additional information that you would like to provide that may be relevant to the issue?

**Comment by Blueeyestar** [comment]
It seems it's my world file? 
When I generate a new world it doesn't come anymore, but can't set any signs with [ATM] either. 

So I can't use the plugin anymore? What could be the reason why Time is Money reacts like this? 

I only use

CMI
CMIEInjector1.0.2.1
Vault
Timeismoney

**Comment by Blueeyestar** [comment]
I found out the mistake!!!

Your plugin reacts to Hopperclock !!
As soon as you have a HopperClock on your server your plugin will fail! I hope you can now solve the problem

**Comment by Blueeyestar** [comment]
I found out the mistake!!!

Your plugin reacts to Hopperclock !!
As soon as you have a HopperClock on your server your plugin will fail! I hope you can now solve the problem 

![2019-05-26_18 11 57](https://user-images.githubusercontent.com/35557302/58384473-1f8a3b00-7fe2-11e9-8e93-d42f6c65e7b9.png)


And you can't make signs with [ATM]. Nothing happens

**Comment by Blueeyestar** [comment]
mastercake10 can you fix the errors?

That would be really great

**Comment by SamLam140330** [comment]
I have the same problem too!
When I am using Timeismoney v1.9.6.5, there was no error. However, **when I update** to v1.9.6.6, it has some error generated.
Full error code: [https://drive.google.com/file/d/1AfA7lOsZdF-AYBai0XIYttwsnUTZYhZe/view?usp=sharing](url)
My server Info:
Version: git-Spigot-1a3504a-dfa7583 (MC: 1.13.2)
Timeismoney: 1.9.6.6
Plugins (47): CoreProtect LuckPerms OreReplacerPlugin OtherBedRegen PlaceholderAPI ClearLag ZavMessage Multiverse-Core AutoRespawnPlus FastAsyncWorldEdit IPWhitelist Multiverse-Inventories ViaVersion Multiverse-NetherPortals Vault DeluxeHub MysqlEcoBridge Essentials QuickBoard KillerMoney ProtocolLib DeluxeChat Citizens EssentialsProtect EssentialsChat EssentialsAntiBuild TimeIsMoney TAB EssentialsSpawn AuthMe Matrix HolographicDisplays CitizensCMD DeathChest PetMaster JH_AuthMeBridge AdvancedAchievements WorldEdit FastAsyncVoxelSniper WorldGuard ExtraHardMode LockettePro MythicMobs WorldGuardRegionClaim RFChairs ChestShop ActionHealth

**Comment by Blueeyestar** [comment]
I figured out the problem... I hope so much he can fix it.

**Comment by aurel85** [comment]
It's ok with 1.9.6.7, thank you !

**Comment by mastercake10** [comment]
> It's ok with 1.9.6.7, thank you !

thanks for the feedback! Always appreciated.
