### ISSUE TITLE
Error while Player AFK and when Starting

### ISSUE THREAD

**Issue by Lapotor** [mastercake10/TimeIsMoney#4]
Hey i run an server on Craftbukkit 1.10.2 (Implementing API version 1.10.2-R0.1-SNAPSHOT) with your Plugin (1.9.3.5) and Essentials Eco (and Vault)
On startup it show this Error:

```
[Server thread/INFO]: [TimeIsMoney] Enabling TimeIsMoney v1928
[Server thread/ERROR]: Error occurred while enabling TimeIsMoney v1928 (Is it up to date?)
java.lang.NullPointerException
    at de.Linus122.TimeIsMoney.Main.loadPayouts(Main.java:235) ~[?:?]
    at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:139) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Bukkit-5e5cf84]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:347) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:319) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:404) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:369) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:324) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:243) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:514) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
```

And when an Player is AFK it say every Second the AFK message of the plugin and this Error in Console:

```
[XX:24:55] [Server thread/WARN]: [TimeIsMoney] Task #93 for TimeIsMoney v1928 generated an exception
java.lang.NullPointerException
    at de.Linus122.TimeIsMoney.Main.sendActionbar(Main.java:398) ~[?:?]
    at de.Linus122.TimeIsMoney.Main.pay(Main.java:343) ~[?:?]
    at de.Linus122.TimeIsMoney.Main$1.run(Main.java:109) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-5e5cf84]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:682) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
[XX:24:56] [Server thread/WARN]: [TimeIsMoney] Task #93 for TimeIsMoney v1928 generated an exception
java.lang.NullPointerException
    at de.Linus122.TimeIsMoney.Main.sendActionbar(Main.java:398) ~[?:?]
    at de.Linus122.TimeIsMoney.Main.pay(Main.java:343) ~[?:?]
    at de.Linus122.TimeIsMoney.Main$1.run(Main.java:109) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-5e5cf84]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:682) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547) [craftbukkit.jar:git-Bukkit-5e5cf84]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
[XX:24:57] [Server thread/WARN]: [TimeIsMoney] Task #93 for TimeIsMoney v1928 generated an exception [...]
```

If you have questions you can come to our Teamspeak3 Server **reden.teamspeak3.de** _(German)_ and look after me or ask some one.

I like your Plugin
See ya

**Comment by mastercake10** [comment]
Hallo,

I've checked the code, first error seems to be a miss configuration of the payouts. Have you ever tried to use the default config one? Just asking before getting deeper in that erorr.

Second error could be the 1.10.2 version, I've not added this yet.
Will do this now.

**Comment by Lapotor** [comment]
OK will try it tomorrow but you mean this part:
payouts:
  1:
    payout_amount: 50
    max_payout_per_day: 1000
    # chance: 10
    permission:

Sry for not using formation I write this from my phone !
