### ISSUE TITLE
[TimeIsMoney] Task #76 for TimeIsMoney v1.9.6.12 generated an exception

### ISSUE THREAD

**Issue by michaelmatteus** [mastercake10/TimeIsMoney#66]
### What steps will reproduce the issue?  

I have no idea

### What was supposed to happen?

Nothing

### What happened instead? 

A lot of errors on the console that never stop even If I disable the plugin, it only stops when I restart the server

### What version of TimeIsMoney are you using?  

TimeIsMoney v1.9.6.12

### What Spigot version are you using? Paste the output of /version below.  

git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  

Plugins (55): AdvancedClans*, AreaReloader*, AsyncWorldEdit, BankSystem, BuyRegion, ChangeSkin*, ChestSort, Citizens, CitizensBooks, CitizensShop, ClearLag, CoreLibs, DynamicShop, EnchantControl, Essentials, EssentialsSpawn, GChestShop, GemsEconomy*, GSit, HolographicDisplays, ID-Library, LuckPerms, mcMMO, MercadoPagoAPI*, MorphShops, Multiverse-Core, nLogin, PagSeguroAPI*, PayPalAPI*, PixelVip*, PL-Hide, PlaceholderAPI, PlayerReport, PlugMan, Poll, ProtocolLib, PvPDiffTimer*, RandomTeleport*, RedProtect, SilkSpawners, SilkSpawnersEcoAddon, SimplePets, SkinsRestorer, SlotZ*, SpigotPing*, TAB, TimeIsMoney*, TradeSystem, UltimateChat, UnexpectedSpawn, Vault, ViaVersion*, WitherAC, WorldEdit, WorldEditSelectionVisualizer

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  

>.... [12:09:43 WARN]: [TimeIsMoney] Task #76 for TimeIsMoney v1.9.6.12 generated an exception
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:518) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:188) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:152) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:121) ~[patched_1.14.4.jar:git-Paper-243]
at me.xanium.gemseconomy.GemsEconomy.doSync(GemsEconomy.java:188) ~[?:?]
at me.xanium.gemseconomy.economy.Account.deposit(Account.java:51) ~[?:?]
at me.xanium.gemseconomy.vault.GEVaultHook.depositPlayer(GEVaultHook.java:144) ~[?:?]
at de.Linus122.TimeIsMoney.Main.pay(Main.java:413) ~[?:?]
at de.Linus122.TimeIsMoney.Main.lambda$onEnable$0(Main.java:160) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

### Any additional information that you would like to provide that may be relevant to the issue?

As I said this error appear a lot of times in console, here you can see the longest log: https://pastebin.com/yv7pA54A

**Comment by mastercake10** [comment]
So, how did you disable that plugin? Its a quite common error that occurs when you disable a plugin via PlugMan or such.  I don't really see why this should be an error, since you just need to delete the .jar file if you really want to disable it..

**Comment by michaelmatteus** [comment]
I use plugman

**Comment by mastercake10** [comment]
but why do you want to disable the plugin and expect it to be working at the same time?

**Comment by michaelmatteus** [comment]
I dont disable it before the errors happens...

**Comment by mastercake10** [comment]
Why does the error above then say that the plugin is disabled? Have you got a stack trace / error before you actually disabled the plugin?

**Comment by michaelmatteus** [comment]
it is not deactivated when the error occurs, when I said that I deactivate it because the error occurs, then I activate it again ... remembering that I have already restarted the server and the problem stops, but after some time it starts flooding my console with these errors, that is, while active

**Comment by mastercake10** [comment]
Hmm, that's weird. Can't really help you since I don't know what disables the plugin in the first place, and then spams this error.

**Comment by michaelmatteus** [comment]
I'll try to record the console to see If I can see where this flooding starts..

**Comment by michaelmatteus** [comment]
Here: https://www.youtube.com/watch?v=SJ3KjoXHBE8

1. It happens when a player type /balance at 0:49 of video
2. It hook into essentials when it is enable again

**Comment by mastercake10** [comment]
Hey, thanks for your effort in creating that video.

I did some debugging and installed **EssentialsX**, **GemsEconomy** along with **TimeIsMoney** on a 1.15.2 Paper server. I've created a testing balance and restarted the server afterward. 
The **/balance** command seems to work, it shows the balance and currency from **GemsEconomy**. Same goes for the payouts from **TimeIsMoney**, they're all formatted and appear to be working.

I've discovered that your error comes up as soon as you disable the **GemsEconomy** plugin and enable it again. Im not sure if you did a reload with plugman before, but that seems to be the issue.. I was not able to reconstruct the issue by staying on the server and getting paid by **TimeIsMoney**  in a 20 seconds interval.

But yeah your video shows that you have not reloaded the **GemsEcomomy** plugin via Plugman, so I don't know why it is coming up for you..

**Comment by michaelmatteus** [comment]
I did a huge maintenance and also updated my jar to version 1.15, it's running pretty stable now ... I removed some plugins and updated them too, I imagine the error was being caused by some wrong configuration or some incompatibility plugin ... thanks!
