### ISSUE TITLE
null pointer execption

### ISSUE THREAD

**Issue by loganfre** [mastercake10/TimeIsMoney#9]
I get the following error using the latest build of spigot. It seems after this error no money is payed out.

`[20:16:13 ERROR]: Error occurred while enabling TimeIsMoney v1947 (Is it up to date?)
java.lang.NullPointerException
at de.Linus122.TimeIsMoney.Main.loadPayouts(Main.java:244) ~[?:?]
at de.Linus122.TimeIsMoney.Main.onEnable(Main.java:147) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[craftbukkit.jar:git-Bukkit-4316a8c]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-4316a8c]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-4316a8c]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit.jar:git-Bukkit-4316a8c]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit.jar:git-Bukkit-4316a8c]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit.jar:git-Bukkit-4316a8c]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit.jar:git-Bukkit-4316a8c]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit.jar:git-Bukkit-4316a8c]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit.jar:git-Bukkit-4316a8c]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit.jar:git-Bukkit-4316a8c]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]`

**Comment by mastercake10** [comment]
Please use the newest version, you're using v1947, the newest is v1948. Please close this issue if the error is gone

**Comment by loganfre** [comment]
I downloaded the latest jar from here: https://www.spigotmc.org/resources/time-is-money.12409/download?version=145792

Is there a newer version available somewhere?

**Comment by mastercake10** [comment]
No, this is the newest version. Nevertheless you're using v1947 in your issue.

**Comment by loganfre** [comment]
I downloaded the jar from the above link and extracted it. The plugin.yml file shows version: 1947, even though the link on spigotmc.org shows 1948.
