### ISSUE TITLE
Fatal exception: bound must be positive

### ISSUE THREAD

**Issue by samuelvelero** [mastercake10/TimeIsMoney#96]
### What steps will reproduce the issue?  
Dont know really but I changed recently the configuration:
```
payouts:
  1:
    payout_amount:  1500
    max_payout_per_day: 12000
    #chance: 100
    permission: timeismoney.default
  2:
    payout_amount:  500
    max_payout_per_day: 12000
    #chance:
    permission: timeismoney.donor
```

### What was supposed to happen?
No errors in console.

### What happened instead? 
Errors in console every second.

### What version of TimeIsMoney are you using?  
1.9.6.18

### What Spigot version are you using? Paste the output of /version below.  
INFO This server is running Paper version git-Paper-"4e2f0be" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (13): CommandCost*, dynmap*, Essentials, EssentialsChat, GSit, HolographicDisplays, LuckPerms, PlasmoVoice, ProtocolLib, SkinsRestorer, TimeIsMoney*, UltimateClaims, Vault

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
```
10.07 16:46:19 [Server] WARN [TimeIsMoney] Task #426 for TimeIsMoney v1.9.6.18 generated an exception
10.07 16:46:19 [Server] INFO java.lang.IllegalArgumentException: bound must be positive
10.07 16:46:19 [Server] INFO at java.util.Random.nextInt(Random.java:388) ~[?:?]
10.07 16:46:19 [Server] INFO at de.Linus122.TimeIsMoney.Main.getApplicablePayoutsForPlayer(Main.java:302) ~[?:?]
10.07 16:46:19 [Server] INFO at de.Linus122.TimeIsMoney.Main.pay(Main.java:322) ~[?:?]
10.07 16:46:19 [Server] INFO at de.Linus122.TimeIsMoney.Main.lambda$startPlaytimeWatcher$1(Main.java:212) ~[?:?]
10.07 16:46:19 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
10.07 16:46:19 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
10.07 16:46:19 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
10.07 16:46:19 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
10.07 16:46:19 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
10.07 16:46:19 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
10.07 16:46:19 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
10.07 16:46:19 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
```
### Any additional information that you would like to provide that may be relevant to the issue?
Not really. A little confused about this error. I didn't expected it.

**Comment by mastercake10** [comment]
set `choose-payout-by-chance` back to `false`.

**Comment by mastercake10** [comment]
no response
